<div class="flex items-center justify-between mb-6"><p class="text-sm text-gray-500"><?= $total ?? 0 ?> consultations</p></div>
<form method="GET" action="/admin/consultations" class="bg-white rounded-lg shadow p-4 mb-6 flex gap-3 items-end">
    <div><label class="block text-xs font-medium text-gray-500 mb-1">Search</label><input type="text" name="search" value="<?= esc($filters['search'] ?? '') ?>" placeholder="Name, phone, booking ID" class="w-64 px-3 py-2 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-bronze outline-none"></div>
    <div><label class="block text-xs font-medium text-gray-500 mb-1">Status</label><select name="status" class="px-3 py-2 border border-gray-300 rounded-lg text-sm"><option value="">All</option><?php foreach (['pending','confirmed','completed','cancelled'] as $s): ?><option value="<?= $s ?>" <?= ($filters['status'] ?? '') === $s ? 'selected' : '' ?>><?= ucfirst($s) ?></option><?php endforeach; ?></select></div>
    <div><label class="block text-xs font-medium text-gray-500 mb-1">Payment</label><select name="payment_status" class="px-3 py-2 border border-gray-300 rounded-lg text-sm"><option value="">All</option><?php foreach (['awaiting','submitted','verified','rejected'] as $s): ?><option value="<?= $s ?>" <?= ($filters['payment_status'] ?? '') === $s ? 'selected' : '' ?>><?= ucfirst($s) ?></option><?php endforeach; ?></select></div>
    <button type="submit" class="bg-bronze text-white px-5 py-2 rounded-lg text-sm font-medium">Filter</button>
</form>
<div class="bg-white rounded-lg shadow overflow-hidden">
    <table class="w-full text-sm"><thead class="bg-gray-50 border-b"><tr><th class="px-4 py-3 text-left font-medium text-gray-600">Booking ID</th><th class="px-4 py-3 text-left font-medium text-gray-600">Client</th><th class="px-4 py-3 text-left font-medium text-gray-600">Mode</th><th class="px-4 py-3 text-center font-medium text-gray-600">Payment</th><th class="px-4 py-3 text-center font-medium text-gray-600">Status</th><th class="px-4 py-3 text-right font-medium text-gray-600">Actions</th></tr></thead>
    <tbody class="divide-y"><?php foreach ($consultations ?? [] as $c): ?><tr class="hover:bg-gray-50"><td class="px-4 py-3 font-mono text-xs"><?= esc($c->booking_id) ?></td><td class="px-4 py-3"><?= esc($c->full_name) ?><br><span class="text-xs text-gray-400"><?= esc($c->mobile) ?></span></td><td class="px-4 py-3 capitalize text-xs"><?= esc($c->consultation_mode) ?></td><td class="px-4 py-3 text-center"><span class="text-xs px-2 py-0.5 rounded <?= $c->payment_status === 'verified' ? 'bg-green-100 text-green-700' : ($c->payment_status === 'submitted' ? 'bg-yellow-100 text-yellow-700' : 'bg-gray-100 text-gray-500') ?>"><?= ucfirst($c->payment_status) ?></span></td><td class="px-4 py-3 text-center"><span class="text-xs px-2 py-0.5 rounded <?= $c->booking_status === 'confirmed' ? 'bg-blue-100 text-blue-700' : ($c->booking_status === 'completed' ? 'bg-green-100 text-green-700' : 'bg-gray-100 text-gray-500') ?>"><?= ucfirst($c->booking_status) ?></span></td><td class="px-4 py-3 text-right"><a href="/admin/consultations/view/<?= $c->id ?>" class="text-bronze hover:underline">View</a></td></tr><?php endforeach; ?></tbody></table>
</div>
<?php if (!empty($pager)): ?><div class="mt-4"><?= $pager->links() ?></div><?php endif; ?>
