<form method="POST" action="<?= $faq ? '/admin/faqs/update/'.$faq->id : '/admin/faqs/store' ?>" class="bg-white rounded-lg shadow p-6 max-w-3xl">
    <?= csrf_field() ?>
    <div><label class="block text-sm font-medium text-gray-700 mb-1">Question *</label><input type="text" name="question" required value="<?= esc($faq->question ?? '') ?>" class="w-full px-4 py-2.5 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-bronze outline-none"></div>
    <div class="mt-4"><label class="block text-sm font-medium text-gray-700 mb-1">Answer *</label><textarea name="answer" rows="8" required class="w-full px-4 py-2.5 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-bronze outline-none resize-y"><?= esc($faq->answer ?? '') ?></textarea></div>
    <div class="grid grid-cols-1 md:grid-cols-3 gap-5 mt-5">
        <div><label class="block text-sm font-medium text-gray-700 mb-1">Assign Type</label><select name="assignable_type" class="w-full px-4 py-2.5 border border-gray-300 rounded-lg text-sm"><option value="">Global</option><option value="page" <?= ($faq->assignable_type ?? '') === 'page' ? 'selected' : '' ?>>Page</option><option value="practice_area" <?= ($faq->assignable_type ?? '') === 'practice_area' ? 'selected' : '' ?>>Practice Area</option><option value="blog_post" <?= ($faq->assignable_type ?? '') === 'blog_post' ? 'selected' : '' ?>>Blog Post</option></select></div>
        <div><label class="block text-sm font-medium text-gray-700 mb-1">Assign ID</label><input type="number" name="assignable_id" value="<?= $faq->assignable_id ?? '' ?>" class="w-full px-4 py-2.5 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-bronze outline-none"></div>
        <div><label class="block text-sm font-medium text-gray-700 mb-1">Sort Order</label><input type="number" name="sort_order" value="<?= $faq->sort_order ?? 0 ?>" class="w-full px-4 py-2.5 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-bronze outline-none"></div>
    </div>
    <div class="mt-4"><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="is_published" value="1" <?= ($faq->is_published ?? 1) ? 'checked' : '' ?> class="rounded"> Published</label></div>
    <div class="mt-6 flex justify-end gap-3"><a href="/admin/faqs" class="px-6 py-2.5 border border-gray-300 rounded-lg text-sm hover:bg-gray-50 transition">Cancel</a><button type="submit" class="bg-charcoal text-white px-8 py-2.5 rounded-lg text-sm font-medium hover:bg-gray-800 transition"><?= $faq ? 'Update' : 'Create' ?> FAQ</button></div>
</form>
