<div class="flex items-center justify-between mb-6"><p class="text-sm text-gray-500"><?= $total ?? 0 ?> payments</p></div>
<form method="GET" action="/admin/payments" class="bg-white rounded-lg shadow p-4 mb-6 flex gap-3 items-end">
    <div><input type="text" name="search" value="<?= esc($filters['search'] ?? '') ?>" placeholder="Search..." class="w-64 px-3 py-2 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-bronze outline-none"></div>
    <div><select name="status" class="px-3 py-2 border border-gray-300 rounded-lg text-sm"><option value="">All Status</option><?php foreach (['awaiting','submitted','verified','rejected','refunded'] as $s): ?><option value="<?= $s ?>" <?= ($filters['status'] ?? '') === $s ? 'selected' : '' ?>><?= ucfirst($s) ?></option><?php endforeach; ?></select></div>
    <button type="submit" class="bg-bronze text-white px-5 py-2 rounded-lg text-sm font-medium">Filter</button>
</form>
<div class="bg-white rounded-lg shadow overflow-hidden">
    <table class="w-full text-sm"><thead class="bg-gray-50 border-b"><tr><th class="px-4 py-3 text-left font-medium text-gray-600">ID</th><th class="px-4 py-3 text-left font-medium text-gray-600">Client</th><th class="px-4 py-3 text-right font-medium text-gray-600">Amount</th><th class="px-4 py-3 text-left font-medium text-gray-600">Method</th><th class="px-4 py-3 text-center font-medium text-gray-600">Status</th><th class="px-4 py-3 text-right font-medium text-gray-600">Actions</th></tr></thead>
    <tbody class="divide-y"><?php foreach ($payments ?? [] as $p): ?><tr class="hover:bg-gray-50"><td class="px-4 py-3">#<?= $p->id ?></td><td class="px-4 py-3"><?= esc($p->client_name) ?><br><span class="text-xs text-gray-400"><?= esc($p->mobile) ?></span></td><td class="px-4 py-3 text-right font-bold text-bronze">₹<?= number_format($p->amount) ?></td><td class="px-4 py-3 capitalize text-xs"><?= esc(str_replace('_',' ',$p->payment_method)) ?></td><td class="px-4 py-3 text-center"><span class="text-xs px-2 py-0.5 rounded <?= $p->status === 'verified' ? 'bg-green-100 text-green-700' : ($p->status === 'submitted' ? 'bg-yellow-100 text-yellow-700' : 'bg-gray-100 text-gray-500') ?>"><?= ucfirst($p->status) ?></span></td><td class="px-4 py-3 text-right"><a href="/admin/payments/view/<?= $p->id ?>" class="text-bronze hover:underline">View</a></td></tr><?php endforeach; ?></tbody></table>
</div>
<?php if (!empty($pager)): ?><div class="mt-4"><?= $pager->links() ?></div><?php endif; ?>
