<div class="flex items-center justify-between mb-6"><p class="text-sm text-gray-500"><?= $total ?? 0 ?> enquiries</p></div>
<form method="GET" action="/admin/enquiries" class="bg-white rounded-lg shadow p-4 mb-6 flex gap-3 items-end">
    <div><input type="text" name="search" value="<?= esc($filters['search'] ?? '') ?>" placeholder="Search..." class="w-64 px-3 py-2 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-bronze outline-none"></div>
    <div><select name="status" class="px-3 py-2 border border-gray-300 rounded-lg text-sm"><option value="">All</option><?php foreach (['new','contacted','consultation_booked','converted','closed'] as $s): ?><option value="<?= $s ?>" <?= ($filters['status'] ?? '') === $s ? 'selected' : '' ?>><?= ucfirst(str_replace('_',' ',$s)) ?></option><?php endforeach; ?></select></div>
    <button type="submit" class="bg-bronze text-white px-5 py-2 rounded-lg text-sm font-medium">Filter</button>
</form>
<div class="bg-white rounded-lg shadow overflow-hidden">
    <table class="w-full text-sm"><thead class="bg-gray-50 border-b"><tr><th class="px-4 py-3 text-left font-medium text-gray-600">Name</th><th class="px-4 py-3 text-left font-medium text-gray-600">Contact</th><th class="px-4 py-3 text-left font-medium text-gray-600">Subject</th><th class="px-4 py-3 text-center font-medium text-gray-600">Status</th><th class="px-4 py-3 text-left font-medium text-gray-600">Date</th><th class="px-4 py-3 text-right font-medium text-gray-600">Actions</th></tr></thead>
    <tbody class="divide-y"><?php foreach ($enquiries ?? [] as $e): ?><tr class="hover:bg-gray-50"><td class="px-4 py-3 font-medium"><?= esc($e->name) ?></td><td class="px-4 py-3 text-xs"><?= esc($e->phone ?: $e->email) ?></td><td class="px-4 py-3 text-xs text-gray-500 truncate max-w-[200px]"><?= esc($e->subject ?: $e->legal_matter) ?></td><td class="px-4 py-3 text-center"><span class="text-xs px-2 py-0.5 rounded <?= $e->status === 'new' ? 'bg-red-100 text-red-700' : ($e->status === 'converted' ? 'bg-green-100 text-green-700' : 'bg-gray-100 text-gray-500') ?>"><?= ucfirst(str_replace('_',' ',$e->status)) ?></span></td><td class="px-4 py-3 text-xs text-gray-500"><?= date('M d, Y', strtotime($e->created_at)) ?></td><td class="px-4 py-3 text-right"><a href="/admin/enquiries/view/<?= $e->id ?>" class="text-bronze hover:underline mr-2">View</a></td></tr><?php endforeach; ?></tbody></table>
</div>
<?php if (!empty($pager)): ?><div class="mt-4"><?= $pager->links() ?></div><?php endif; ?>
